2019-11-30 03:01:54,391 - pyiron_log - INFO - job: spx_b_Fe32_3c5_adddf id: 4639938, status: submitted, run job (modal)
2019-11-30 03:05:15,851 - pyiron_log - INFO - job: spx_b_Fe32_3c5_adddf id: 4639938, status: collect, output: srun: error: cmfe193: tasks 19,26,34: Broken pipe
srun: Terminating job step 88774.1
slurmstepd: error: *** STEP 88774.1 ON cmfe193 CANCELLED AT 2019-11-30T03:05:15 ***
srun: error: cmfe193: tasks 0-18,20-25,27-33,35-39: Terminated
srun: Force Terminated job step 88774.1

2019-11-30 03:05:15,851 - pyiron_log - INFO - run job: spx_b_Fe32_3c5_adddf id: 4639938, status: collect
/u/samsstud/dev_sam/pyiron/pyiron/sphinx/base.py:1547: UserWarning: SPHInX parsing failed; most likely SPHInX crashed.
  warnings.warn("SPHInX parsing failed; most likely SPHInX crashed.")
Traceback (most recent call last):
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/u/samsstud/dev_sam/pyiron/pyiron/base/job/wrappercmd.py", line 52, in <module>
    command_line(sys.argv[1:])
  File "/u/samsstud/dev_sam/pyiron/pyiron/base/job/wrappercmd.py", line 46, in command_line
    submit_on_remote=submit_on_remote
  File "/u/samsstud/dev_sam/pyiron/pyiron/base/job/wrapper.py", line 147, in job_wrapper_function
    job.run()
  File "/u/samsstud/dev_sam/pyiron/pyiron/base/job/wrapper.py", line 113, in run
    self.job.run_static()
  File "/u/samsstud/dev_sam/pyiron/pyiron/base/job/generic.py", line 762, in run_static
    self.run()
  File "/u/samsstud/dev_sam/pyiron/pyiron/base/job/generic.py", line 675, in run
    self._run_if_collect()
  File "/u/samsstud/dev_sam/pyiron/pyiron/base/job/generic.py", line 1392, in _run_if_collect
    self.collect_output()
  File "/u/samsstud/dev_sam/pyiron/pyiron/sphinx/base.py", line 688, in collect_output
    self._output_parser.collect(directory=self.working_directory)
  File "/u/samsstud/dev_sam/pyiron/pyiron/sphinx/base.py", line 1768, in collect
    self.collect_sphinx_log(file_name="sphinx.log", cwd=directory)
  File "/u/samsstud/dev_sam/pyiron/pyiron/sphinx/base.py", line 1549, in collect_sphinx_log
    0
IndexError: index 0 is out of bounds for axis 0 with size 0
